name: torus-theory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scipy
  - gwpy
  - jupyter
  - zstandard
  - h5py
  - pytest
  - black[jupyter]
  - papermill
  - nbconvert
  - jupyterlab # provides kernelspec CLI
  - nbclient
  - click
  - ruff
