# autogenerated by Copilot root-sweep-2
mkdir -p docs/figures/
git mv "entropy_analyze-05-01-2025_01_03_AM.png" "docs/figures/entropy_analyze-05-01-2025_01_03_AM.png"
git mv "timing_stats-05-01-2025_12_56_PM.png" "docs/figures/timing_stats-05-01-2025_12_56_PM.png"

mkdir -p data/entropy/
git mv "entropy_counts.csv" "data/entropy/entropy_counts.csv"
git mv "entropy_raw.bin" "data/entropy/entropy_raw.bin"

mkdir -p data/bicycle/
git mv "timing.csv" "data/bicycle/timing.csv"

mkdir -p docs/
git mv "checksums_v1.1.txt" "docs/checksums_v1.1.txt"
git mv "repo_plan.md" "docs/repo_plan.md"
git mv "SCALING_NOTICE.md" "docs/SCALING_NOTICE.md"

mkdir -p docs/papers/
git mv "torus_book.pdf" "docs/papers/torus_book.pdf"
git mv "torus_book.aux" "docs/papers/torus_book.aux"
git mv "torus_book.log" "docs/papers/torus_book.log"

mkdir -p scripts/
git mv "populate_placeholders.sh" "scripts/populate_placeholders.sh"
git mv "restore_structure.sh" "scripts/restore_structure.sh"
git mv "chi_modtime.py" "scripts/chi_modtime.py"
git mv "entropy_drift_pure.py" "scripts/entropy_drift_pure.py"
git mv "extract_doppler.py" "scripts/extract_doppler.py"
git mv "repair_notebooks.py" "scripts/repair_notebooks.py"
git mv "stack_timing.py" "scripts/stack_timing.py"

# Files requiring human review
# FLRS00PRT_S_20250550000_01D_EN.rnx
# task_list.json
# requirements.txt
# requirements-dev.txt
# pyproject.toml
# recursive_controller_validation.ipynb