name: Build & Sync Book

on:
  push:
    branches:
      - main
    paths:
      - 'docs/book/**/*.docx'
      - '.github/workflows/book_pipeline.yml'
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository on main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: false
          fetch-depth: 0
      - name: Debug repository state
        run: |
          git status
          git branch -a
          if [ -f .gitmodules ]; then cat .gitmodules; else echo ".gitmodules not present"; fi
      - name: Ensure the repository is on the correct branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-full fonts-lmodern \
                                 texlive-xetex texlive-lang-all \
                                 texlive-fonts-recommended texlive-latex-extra \
                                 texlive-extra-utils   # provides lacheck
      - name: Audit and Regenerate DOCX for Native Equations
        run: scripts/audit_and_regen_docx.sh
      - name: Convert DOCX → LaTeX
        run: scripts/convert_docx_to_tex.sh
      - name: Validate LaTeX Inputs
        run: |
          refs=$(grep -Eo '\\(includegraphics|input|include)\{[^}]+\}' -R docs/book-latex | sed 's/.*{//;s/}//')
          for f in $refs; do
            if [ ! -e "docs/book-latex/$f" ] && [ ! -e "docs/book-latex/${f}.tex" ]; then
              echo "::error::Missing file $f"
              exit 1
            fi
          done
          find docs/book-latex/ -name "*.tex" -exec lacheck {} +
      - name: Initialize and Update Submodules
        run: |
          git submodule init
          git submodule update --recursive
      - name: Clean LaTeX build artifacts
        run: |
          git clean -fdX
      - name: Commit updated .tex mirror
        run: |
          git config user.name  "docx-sync-bot"
          git config user.email "bot@users.noreply.github.com"
          git checkout main  # Ensure the repository is on the main branch
          git add docs/book-latex
          git diff --cached --quiet || git commit -m "CI: auto-sync .tex mirror"
          git push origin main
      - name: Cleanup Generated Files
        run: |
          rm -rf *.aux *.log *.out *.toc
      - name: Cleanup
        working-directory: docs/book-latex
        run: rm -f *.aux *.bbl *.blg *.log *.out *.toc
      - name: Clean LaTeX Auxiliary Files
        working-directory: docs/book-latex
        run: latexmk -c
      - name: CI LaTeX Macro & Tab Check
        working-directory: docs/book-latex
        run: ./ci_latex_check.sh
      - name: Build PDF
        id: build
        working-directory: docs/book-latex
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error torus_book.tex
      - name: Dump LaTeX log on failure
        if: failure() && steps.build.outcome == 'failure'
        working-directory: docs/book-latex
        run: |
          echo "------ torus_book.log (tail) ------"
          tail -n 200 torus_book.log || true
      - name: Debug LaTeX File
        working-directory: docs/book-latex
        run: |
          grep -i "missing" torus_book.log || echo "No missing characters detected"
      - name: Debug LaTeX Issues (Optional)
        if: failure()
        working-directory: docs/book-latex
        run: cat torus_book.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TORUS-Book
          path: docs/book-latex/torus_book.pdf