name: CI Skeleton
on: 
  - push
  - pull_request
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify CI skeleton
        run: echo "CI skeleton OK"
      - name: Validate chapters folder
        run: |
          if [ ! -d "docs/book/chapters/" ]; then
            echo "Warning: docs/book/chapters/ folder is missing."
          elif ! find docs/book/chapters/ -type f -name "*.docx" | grep -q .; then
            echo "Warning: No DOCX files found in docs/book/chapters/."
          fi
