name: CI Skeleton
on: 
  - push
  - pull_request
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify CI skeleton
        run: echo "CI skeleton OK"
