name: LaTeX PDF Build

on:
  push:
    paths:
      - 'docs/book-latex/torus_book.tex'
      - 'docs/style/torus_macros.tex'
      - 'docs/book-latex/**.tex'
      - 'docs/supplements/**.tex'
      - 'docs/validation/**.tex'
      - '.github/workflows/latex.yml'

jobs:
  pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - docs/book-latex/frontmatter/Table_of_Contents.tex
          - docs/book-latex/frontmatter/00_Preface.tex
          - docs/book-latex/torus_book.tex
    steps:
      - uses: actions/checkout@v4
      - uses: dante-ev/latex-action@v2
        with:
          root_file: ${{ matrix.file }}
          engine: xelatex
          extra_packages: "unicode-math physics siunitx xcolor"
