name: TORUS – one-shot file organizer
on: workflow_dispatch
jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: batch moves
        run: |
          bash <<'SCRIPT'
          set -euo pipefail
          mkdir -p docs/book/frontmatter docs/book/chapters docs/book/appendices \
                   docs/papers docs/validation docs/experiments
          while read -r s d; do
            git mv -f "$s" "$d" || true
          done <<'MAP'
          # (paste the same src→dest map Halcyon provided)
          MAP
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Automated file-organize workflow run"
          SCRIPT
      - name: push
        run: git push
