name: Publish SimLab Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'simlab-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build SimLab Docker image
        run: |
          docker build -t ghcr.io/genghisdarb/torus-simlab:${{ github.ref_name }} -f docker/torus-simlab/Dockerfile .

      - name: Push SimLab Docker image
        run: |
          docker push ghcr.io/genghisdarb/torus-simlab:${{ github.ref_name }}
