name: Build validation release

on:
  push:
    tags: ["v*"]         # any tag starting with “v”, e.g. v1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0   # makes sure the tag commit is present

    # (optional) run quick reproducibility checks here
    # - name: Run sanity script
    #   run: bash scripts/quick_validate.sh

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        draft: false
        artifacts: |
          data/**/*
          notebooks/**/*.{ipynb,nb}
          figures/**/*.{png,pdf}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to Zenodo
      if: ${{ secrets.ZENODO_TOKEN != '' }}
      uses: openjournals/zenodo-action@v1
      with:
        token: ${{ secrets.ZENODO_TOKEN }}
